version: "3.7"

services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    env_file: .env
    volumes:
      - mysql_data:/var/lib/mysql
    command: mysqld --explicit_defaults_for_timestamp=1
  api:
    container_name: actix-todo-dev-api-dev
    command: bash -c "./init.sh & bash"
    tty: true
    volumes:
      - ./actix-backend/:/app/
    depends_on:
      - db
volumes:
  mysql_data:
